### ISSUE TITLE
Mi primera clase (avión)

### ISSUE THREAD

**Issue by chisela14** [chisela14/Junio#2]
Buenas tardes Inma, he subido el ejercicio de la primera clase.

**Comment by ioliasa** [comment]
¿Por qué en asignar vuelo le quitas a capacidad el número de asientos que van ocupados?
El toString no lo has hecho, y aunque no se pida acostúmbrate a hacer el hashcode y el equal. Te hará falta más adelante.

**Comment by chisela14** [comment]
Lo hice para poder controlar cuántos asientos se ocupaban en varias asignaciones de vuelo sin utilizar un nuevo atributo que no estaba en el uml. Podría haberlo hecho con un atributo de asientos ocupados, ¿lo añado?.

**Comment by ioliasa** [comment]
No, lo único que tienes que hacer es comprobar que el número de asientos ocupados es menor que la capacidad. La capacidad es una característica del avión, y los asientos ocupados, sería de vuelo si quisieramos guardarlo, pero no es el caso
