### ISSUE TITLE
Ej persona

### ISSUE THREAD

**Issue by chisela14** [chisela14/Junio#3]
Buenos días Inma, he subido el ej de la clase Persona.

**Comment by ioliasa** [comment]
Pone que la longitud por defecto sea 8, pero que dejes preparada la clase para que sea fácil cambiarla. Ahí te está diciendo que uses una constante en vez del 8, si luego se cambia, sólo cambio el valor de la constante.
En generaPassword, cuando creas la variable Ramdon y la inicializas, lo estás haciendo muchas veces, tantas como longitud, eso es mejor sacarlo del bucle. Mira la diferencia entre String y StringBuilder, aquí yo usaria StringBuilder.
El llamar a super() en el constructor tiene sentido cuando tienes herencia, si no, no lo tiene.

En persona el sexo debería ser un enumerado.
generaDni es privado

**Comment by chisela14** [comment]
Ya lo he cambiado todo, incluido lo de encontrar palabra en el ej de strings, ¿el enumerado así está bien?

**Comment by ioliasa** [comment]
Revisa lo que hemos visto en clase
