### ISSUE TITLE
Bloc de notas

### ISSUE THREAD

**Issue by chisela14** [chisela14/Junio#5]
Hola Inma, no me queda claro como interacciona el bloc con notaAlarma. Por ejemplo para el método de añadir una nota, ¿tengo que hacer un método para añadir una nota y otro para añadir una notaAlarma?

**Comment by chisela14** [comment]
Buenas tardes Inma, ¿puedes revisar el ejercicio a ver si me falta algo o así ya está bien?

**Comment by ioliasa** [comment]
En eliminarNota, no tienes un elemento menos, lo que haces es duplicar el siguiente del que quieres borrar. Además, ¿qué pasa si quieres borrar el último?
En getNota, tienes que comprobar que la nota existe, al igual que en updateNota, activa y desactiva.

**Comment by chisela14** [comment]
Lo he cambiado.
