### ISSUE TITLE
Cartas

### ISSUE THREAD

**Issue by chisela14** [chisela14/Junio#6]
Buenas tardes Inma, estoy intentando crear una baraja en el main y se me queda el programa trabajando mucho rato. He hecho el debugger en baraja y juraría que no es un bucle infinito pero no estoy segura. ¿Cuánto debería tardar en crearme la baraja?
¿Lo demás cómo está?

**Comment by ioliasa** [comment]
Buenos días Chisela, si se te queda en un bucle infinito tiene toda la pinta que no termina de barajar, mira si tienes más cartas, que las que puede generar, es decir, si tienes por ejemplo 40 cartas y sólo genera 20 diferentes, por mucho que generes estará repetida y no la meterá, por lo que nunca terminará
