### ISSUE TITLE
Ejercicios 3Ev

### ISSUE THREAD

**Issue by chisela14** [chisela14/Junio#8]
Buenos días Inma, he hecho los ejercicios 1 y 2 de la carpeta ejercicios.

**Comment by ioliasa** [comment]
Lo de genérico no es con object, pero mejor te lo explico el viernes en clase. Recuérdalme si se me olvida

**Comment by chisela14** [comment]
En un principio lo pensé buscado el alumno, pero como dice que devuelva el alumno si existe ¿por qué tengo que buscarlo? lo he cambiado, ¿sería así?
Lo empecé a hacer con un set pero pide exception si el alumno ya existe ¿se puede manejar esa exception con set? porque probé a añadir dos iguales y simplemente no lo añadía. Usé el linkedlist por si se borraba algún alumno en medio.

**Comment by chisela14** [comment]
Pero entonces en el ejercicio dos ¿como sé cuál es la última página que tiene ese día?

**Comment by ioliasa** [comment]
> En un principio lo pensé buscado el alumno, pero como dice que devuelva el alumno si existe ¿por qué tengo que buscarlo? lo he cambiado, ¿sería así?

Si, así sería, estás devolviendo el objeto que tienes en la colecction.


> Lo empecé a hacer con un set pero pide exception si el alumno ya existe ¿se puede manejar esa exception con set? porque probé a añadir dos iguales y simplemente no lo añadía. Usé el linkedlist por si se borraba algún alumno en medio.

Cuando añades un elemento al set te devuelve un booleano indicando si ha podido añadirlo o no, si ya está no puede añadirlo y devuelve false, por lo que tu debes ser la que lance la exception. En este caso con Set puedes borrar en cualquier sitio ya que el orden no importa

**Comment by ioliasa** [comment]
> Pero entonces en el ejercicio dos ¿como sé cuál es la última página que tiene ese día?

Cuando el día sea superior al que estés buscando. A partir de ahí ya estás segura que no vas a encontrar nada

**Comment by chisela14** [comment]
He cambiado el 1 (solo el normal, el genérico no) para hacerlo con set y he cambiado el método del ejercicio 2.
También he subido el ej 3.

**Comment by chisela14** [comment]
Buenas tardes Inma, en el ejercicio 4 ¿te importa si las pruebas del main las hago como están? si lo hago como un menú para el usuario cada vez que quiero probar algo tengo que introducir varias palabras.
A la hora de listar palabras que empiezan por una cadena he creado dos que empiezan por "te" pero solo aparece una ¿qué está mal?

**Comment by chisela14** [comment]
El ejercicio 5 es el 4 pero con mapas. Había pensado hacer un mapa con las letras de clave y un array de palabras como valor, ¿se hace así o de otra forma?

**Comment by ioliasa** [comment]
> Buenas tardes Inma, en el ejercicio 4 ¿te importa si las pruebas del main las hago como están? si lo hago como un menú para el usuario cada vez que quiero probar algo tengo que introducir varias palabras. A la hora de listar palabras que empiezan por una cadena he creado dos que empiezan por "te" pero solo aparece una ¿qué está mal?

Probarlo puedes hacerlo como quieras, en relación a que sólo te sale una, lo que me extraña es que te salga una, si la primera palabra no empieza por lo que tu quieres se saldrá del bucle, ahi tienes que tener un bucle y un if dentro. Por otro lado ten cuidado porque cada vez que usas iterator.next pasas al siguiente elemento. Mañana lo vemos en clase

**Comment by ioliasa** [comment]
> El ejercicio 5 es el 4 pero con mapas. Había pensado hacer un mapa con las letras de clave y un array de palabras como valor, ¿se hace así o de otra forma?

Yo más bien podnría un mapa en el que la clave sea la palabra y tenga un conjunto de string que son los significados, lo que tu planteas podría ser una segunda versión mejorada de lo que yo te digo, pero creo que como yo te lo propongo es más fácil.`

**Comment by chisela14** [comment]
Buenos días Inma, ya he revisado los ejercicios del 1-4 y he hecho el 5.
